version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
      timezone: Europe/Berlin
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      # EST timezone
      timezone: "America/New_York"
    rebase-strategy: "auto"
    open-pull-requests-limit: 0
    commit-message:
      # Prefix all commit messages with "chore"
      # include a list of updated dependencies
      prefix: "chore(deps):"
    labels:
      - "dependencies"
