version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
      timezone: Europe/Berlin
  # DO NOT ENABLE UNTIL RESOLVED
  # https://github.com/dependabot/dependabot-core/issues/1297
  # - package-ecosystem: npm
  #   directory: '/'
  #   schedule:
  #     interval: 'daily'
