[relaychain]
default_command = "../polkadot"
default_args = [ "-lparachain=debug" ]
chain_spec_path = "./paseo-local.plain.json"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "-lparachain=debug" ]
  ws_port = 9900

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  validator = true
  extra_args = [ "-lparachain=debug" ]

[[parachains]]
id = 1000
addToGenesis = true
chain_spec_path = "./asset-hub-paseo-local.plain.json"
cumulus_based = true

  [[parachains.collators]]
  name = "paseo-asset-hub-collator01"
  command = "../polkadot-parachain"
  args = ["--log=xcm=trace,pallet-assets=trace"]
  ws_port = 9933

  [[parachains.collators]]
  name = "paseo-asset-hub-collator02"
  command = "../polkadot-parachain"
  ws_port = 9911
  args = ["--log=xcm=trace,pallet-assets=trace"]
