name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate docs
        run: |
          yarn install
          yarn build
          yarn docs
          git add .
          git commit -m "docs: Generate docs"
          git push
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}